use std::error::Error;
use std::fmt::{Display, Formatter};
use std::io;

/// The single error type this crate should surface to all callers.
#[derive(Debug)]
pub enum SoraError {
  /// We haven't received a bearer token yet
  /// This is our own internal application state error, not something Sora returns.
  NoBearerTokenAvailable,

  /// We're sending too many tasks to Sora.
  TooManyConcurrentTasks,

  // TODO: Try to make concrete error types for these.
  /// Unauthorized, cookie and/or bearer token expired. We'll need to ask for a refreshed login.
  ///
  /// Example message, e.g. from the upload endpoint:
  ///   {
  ///     "error": {
  ///       "message": "Your authentication token has expired. Please try signing in again.",
  ///       "type": "invalid_request_error",
  ///       "param": null,
  ///       "code": "token_expired"
  ///     }
  ///   }
  UnauthorizedCookieOrBearerExpired,
  
  /// Failed to generate a bearer token despite the `200 OK` response.
  /// This has been generated by sending old/expired session cookies or empty cookies.
  FailedToGenerateBearer,
  
  /// Sora requires users to set up an account username before they can generate images.
  /// This requires the user to set up that username.
  SoraUsernameNotYetCreated,

  /// Something is wrong with the JWT bearer token.
  /// This error originates on our end as we try to parse the JWT.
  LocalJwtClaimsParseError(String),
  
  /// Sora is having issues.
  /// Typically served from Cloudflare
  /// We preserve the message for debugging.
  BadGateway(String),
  
  /// HTTP 524 (Cloudflare-specific)
  /// Cloudflare formed a TCP connection to Sora, but no payload was delivered before timeout
  /// We preserve the message for debugging
  CloudFlareTimeout(String),

  /// Another error occurred.
  OtherBadStatus(anyhow::Error),

  /// Reqwest Error, eg. connection failures.
  ReqwestError(reqwest::Error),

  /// std::io Error that arises from our end, eg. reading from the filesystem.
  IoError(io::Error),

  /// anyhow::Error arises from our end
  AnyhowError(anyhow::Error),

  /// serde_json::Error, likely from JSON deserialization schema mismatch.
  JsonError(serde_json::Error),

  /// serde_json::Error, likely from JSON deserialization schema mismatch.
  /// Includes the original body.
  JsonErrorWithBody(serde_json::Error, String),
}

impl Error for SoraError {}

impl Display for SoraError {
  fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
    match self {
      Self::NoBearerTokenAvailable => {
        write!(f, "Unauthorized: no bearer token set")
      }
      Self::FailedToGenerateBearer => {
        write!(f, "Failed to generate bearer. Probably invalid session.")
      }
      Self::SoraUsernameNotYetCreated => {
        write!(f, "Sora username not created. Please set up a username.")
      }
      Self::LocalJwtClaimsParseError(message) => {
        write!(f, "Local JWT claims parse error: {}", message)
      }
      Self::TooManyConcurrentTasks => {
        write!(f, "Too many concurrent tasks. Please wait.")
      }
      Self::UnauthorizedCookieOrBearerExpired => {
        write!(f, "Unauthorized: cookie and/or bearer token expired")
      }
      Self::BadGateway(message) => {
        write!(f, "Bad Gateway; Sora is likely having issues: {:?}", message)
      }
      Self::CloudFlareTimeout(message) => {
        write!(f, "Cloudflare Timeout (524); Sora is likely having issues: {:?}", message)
      }
      Self::OtherBadStatus(err) => {
        write!(f, "Other error: {}", err)
      }
      Self::ReqwestError(err) => {
        write!(f, "Reqwest error: {}", err)
      }
      Self::IoError(err) => {
        write!(f, "IO error: {}", err)
      }
      Self::AnyhowError(err) => {
        write!(f, "Anyhow error: {}", err)
      }
      Self::JsonError(err) => {
        write!(f, "serde_json error: {}", err)
      }
      Self::JsonErrorWithBody(err, message) => {
        write!(f, "serde_json error: {:?} body: {:?}", err, message)
      }
    }
  }
}

impl From<reqwest::Error> for SoraError {
  fn from(err: reqwest::Error) -> SoraError {
    Self::ReqwestError(err)
  }
}

impl From<io::Error> for SoraError {
  fn from(err: io::Error) -> Self {
    Self::IoError(err)
  }
}

impl From<anyhow::Error> for SoraError {
  fn from(err: anyhow::Error) -> Self {
    Self::AnyhowError(err)
  }
}

impl From<serde_json::Error> for SoraError {
  fn from(err: serde_json::Error) -> Self {
    Self::JsonError(err)
  }
}
