pub mod create_user_bookmark_handler;
pub mod delete_user_bookmark_handler;
pub mod list_user_bookmarks_for_entity_handler;
pub mod list_user_bookmarks_for_session_handler;
pub mod list_user_bookmarks_for_user_handler;
