export enum DialogAddMediaStatuses {
  STAGING_FILE = "STAGING_FILE",
  FILE_UPLOADING = "FILE_UPLOADING",
  FILE_UPLOADED = "FILE_UPLOADED",
  ERROR_FILE_UPLOAD = "ERROR_FILE_UPLOAD",
  FILE_RECORD_REQUESTING = "FILE_RECORD_REQUESTING",
  FILE_RECORD_RECEIVED = "FILE_RECORD_RECEIVED",
  ERROR_FILE_RECORD_REQUEST = "ERROR_FILE_RECORD_REQUEST",
}
