import { signal } from "@preact/signals-core";
import { AssetType } from "~/enums";
import { MediaItem } from "~/pages/PageEnigma/models";

export const demoAnimationItems = signal<MediaItem[]>([
  {
    version: 1,
    media_id: "m_yzreg1494d08aepezj74607d2ascep",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Sit",
    thumbnail: "/resources/characters/img04.png",
    isMine: true,
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_qepzjytd4ahd5askdt2ngrwzj2aa3f",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Idle",
    thumbnail: "/resources/characters/img07.png",
    isBookmarked: true,
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_s7d4ems68sb2vqj4pdje1rc15q3ycp",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Walk",
    thumbnail: "/resources/characters/img07.png",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_v06h821hj4dvst0mzm575jdka31f41",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Punch",
    thumbnail: "/resources/characters/img08.png",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_q92keqa05gds69zyd8mkep7z9338t8",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Jump",
    thumbnail: "/resources/characters/img06.png",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_0qmgsyxh5ng9c9ac3m0snzdqqs5q60",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Dance",
    thumbnail: "/resources/characters/img11.png",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_4ydax69ystd9tzq8m714jrdqcc6nvw",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Jump Forward",
    thumbnail: "/resources/characters_gif/Jump Forward.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_rhscc6zrt9sftpwvx2xyf965a5mh4p",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Tonic Seizure",
    thumbnail: "/resources/characters_gif/Tonic Seizure.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_xd30y703zeqke26j7v9qh5cnzwn0h9",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Ginga Variation 3",
    thumbnail: "/resources/characters_gif/Ginga Variation 3.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_jggmpzjvy68pyt8v4n3nxqfy80kqbg",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Texting",
    thumbnail: "/resources/characters_gif/Texting.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_xezj4qpe5mav3gv4vbfjksvhctb365",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Pushing",
    thumbnail: "/resources/characters_gif/Pushing.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_4fyxtbk4fxz312cc6y4bs5y739x4dc",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Texting While Standing",
    thumbnail: "/resources/characters_gif/Texting While Standing.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_zxdethnpahecz2v0nj0k4xjehdb3ne",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Getting Bit",
    thumbnail: "/resources/characters_gif/Getting Bit.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_m27a9jwh96xe270pgxcjwg88c0a01j",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Twist Dance",
    thumbnail: "/resources/characters_gif/Twist Dance.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_9ejtr55r3s84gpek5wxn1v4apcjff7",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Peek Around Corner",
    thumbnail: "/resources/characters_gif/Femme Peek Around Corner.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_1cvqm136nsjgnkzst9rc4w5rgfefxj",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Sword And Shield Casting",
    thumbnail: "/resources/characters_gif/Sword And Shield Casting.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_hndk99w0knxmxvm23vshyybwace9hx",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Breakdance Ready",
    thumbnail: "/resources/characters_gif/Breakdance Ready.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_30ak4bj738gs8eax3bz8b7nyg55x4d",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Sitting Yell",
    thumbnail: "/resources/characters_gif/Sitting Yell.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_hj31108d09zsvsv2r8rbb3j9vkas06",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Uppercut",
    thumbnail: "/resources/characters_gif/Uppercut.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_fzsrqv5bcyk4fq6ewx93sztbxgcnf2",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Breakdance Uprock Var 1",
    thumbnail: "/resources/characters_gif/Breakdance Uprock Var 1.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_8bsmytdf4ak7kazkj78sfexpx6wvwy",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Standard Walk",
    thumbnail: "/resources/characters_gif/Standard Walk.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_hw99268jayaw8nxy7nf9hvn4ep88xb",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Sword And Shield Jump",
    thumbnail: "/resources/characters_gif/Sword And Shield Jump.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_3rrqez1yb8efm7wne4m9kbaeda1270",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Baseball Bunt",
    thumbnail: "/resources/characters_gif/Baseball Bunt.gif",
    media_type: "glb",
  },

  {
    version: 1,
    media_id: "m_19cz9a2wdgbpn99tx9gdtw3t7t1k6h",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Sneaking Forward",
    thumbnail: "/resources/characters_gif/Sneaking Forward.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_0sm2ycm3napvsqhgbm06nkv6x48vqj",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Right Strafe Walking",
    thumbnail: "/resources/characters_gif/Right Strafe Walking.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_xvq7ybyjmwsebhxw31kxn5v0pksjvf",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Laying Breathless",
    thumbnail: "/resources/characters_gif/Laying Breathless.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_vrwzar5kwm2p1crtcxvxqmpxv7dt9x",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Orc Walk",
    thumbnail: "/resources/characters_gif/Orc Walk.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_f6zvavya6n9zdkhd4nzh5s9wj39zwn",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Run Look Back",
    thumbnail: "/resources/characters_gif/Run Look Back.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_p3fzg4p0d46xwq2qk0chrvmht4xx9v",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Lengthy Head Nod",
    thumbnail: "/resources/characters_gif/Lengthy Head Nod.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_aazz0c3e1ygdawhny6vxm9yyw0t00d",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Right Hook",
    thumbnail: "/resources/characters_gif/Right Hook.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_1c7enn6wzsb44qw26azpb9ewecmja8",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Great Sword Impact",
    thumbnail: "/resources/characters_gif/Great Sword Impact.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_xy9p9x6bnq0nc4tb7ajb7hh91hk1ec",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Zombie Biting",
    thumbnail: "/resources/characters_gif/Zombie Biting.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_7e2gmcwy1t6bbkwetn1ad7fmtg15ek",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Leaning",
    thumbnail: "/resources/characters_gif/Leaning.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_3dkcn3c1j160xvbe1haqprmsb566qg",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Corkscrew Evade",
    thumbnail: "/resources/characters_gif/Corkscrew Evade.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_x8kndshp2psy8cx7r4z13m3hkp7t1t",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Catwalk Walk Forward Crossed",
    thumbnail: "/resources/characters_gif/Catwalk Walk Forward Crossed.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_zhp9kzjwq1ek1618kzk88a0c7nv4y4",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Look Around",
    thumbnail: "/resources/characters_gif/Look Around.gif",
    media_type: "glb",
  },
  {
    version: 1,
    media_id: "m_b1vkd8hj22mnhgsxx00vg8aha8pxda",
    type: AssetType.ANIMATION,
    length: 100,
    name: "Convulsing",
    thumbnail: "/resources/characters_gif/Convulsing.gif",
    media_type: "glb",
  },
]);
