CREATE TABLE model_weights (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  token VARCHAR(32) NOT NULL,
  weights_type VARCHAR(32) NOT NULL,
  weights_category VARCHAR(32) NOT NULL,
  title VARCHAR(255) NOT NULL,
  maybe_thumbnail_token VARCHAR(32) DEFAULT NULL,
  description_markdown TEXT NOT NULL,
  description_rendered_html TEXT NOT NULL,
  creator_user_token VARCHAR(32) NOT NULL,
  creator_ip_address VARCHAR(40) NOT NULL,
  creator_set_visibility ENUM(
    'public',
    'hidden',
    'private'
  ) NOT NULL DEFAULT 'public',
  maybe_last_update_user_token VARCHAR(32) DEFAULT NULL,
  original_download_url VARCHAR(512) DEFAULT NULL,
  original_filename VARCHAR(255) DEFAULT NULL,
  file_size_bytes INT(10) NOT NULL DEFAULT 0,
  file_checksum_sha2 CHAR(64) NOT NULL,
  public_bucket_hash  VARCHAR(32) NOT NULL,
  maybe_public_bucket_prefix VARCHAR(16) DEFAULT NULL,
  maybe_public_bucket_extension VARCHAR(16) DEFAULT NULL,
  cached_user_ratings_total_count INT(10) UNSIGNED NOT NULL DEFAULT 0,
  cached_user_ratings_positive_count INT(10) UNSIGNED NOT NULL DEFAULT 0,
  cached_user_ratings_negative_count INT(10) UNSIGNED NOT NULL DEFAULT 0,
  maybe_cached_user_ratings_ratio FLOAT,
  cached_user_ratings_last_updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  user_deleted_at TIMESTAMP NULL,
  mod_deleted_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;