mod comments_routes;
mod credits_routes;
mod featured_item_routes;
mod generate_routes;
mod job_routes;
mod media_files_routes;
mod moderation_routes;
mod stripe_artcraft_routes;
mod subscription_routes;
mod tag_routes;
mod user_bookmarks_routes;
mod user_rating_routes;
mod user_routes;
mod webhook_routes;
mod weights_routes;
pub (super) mod add_application_routes;
mod prompts_routes;
mod analytics_routes;