use crate::common::responses::media_file_cover_image_details::MediaFileCoverImageDetails;
use crate::common::responses::media_links::MediaLinks;
use crate::common::responses::user_details_light::UserDetailsLight;
use chrono::{DateTime, Utc};
use enums::by_table::media_files::media_file_class::MediaFileClass;
use enums::by_table::media_files::media_file_type::MediaFileType;
use enums::common::visibility::Visibility;
use serde_derive::{Deserialize, Serialize};
use tokens::tokens::batch_generations::BatchGenerationToken;
use tokens::tokens::media_files::MediaFileToken;
use tokens::tokens::prompts::PromptToken;
use utoipa::ToSchema;

/// For the URL PathInfo
#[derive(Serialize, Deserialize, ToSchema)]
pub struct ListBatchGeneratedMediaFilesPathInfo {
  pub token: BatchGenerationToken,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct ListBatchGeneratedMediaFilesSuccessResponse {
  pub success: bool,
  pub media_files: Vec<BatchGeneratedMediaFileInfo>,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct BatchGeneratedMediaFileInfo {
  pub token: MediaFileToken,

  /// The coarse-grained class of media file: image, video, etc.
  pub media_class: MediaFileClass,

  /// Type of media will dictate which fields are populated and what
  /// the frontend should display (e.g. video player vs audio player).
  /// This is closer in meaning to a "mime type".
  pub media_type: MediaFileType,

  /// If the file was generated as part of a batch, this is the token for the batch.
  pub maybe_batch_token: Option<BatchGenerationToken>,

  /// Rich CDN links to the media, including thumbnails, previews, and more.
  pub media_links: MediaLinks,

  /// Information about the cover image. Many media files do not require a cover image,
  /// e.g. image files, video files with thumbnails, audio files, etc.
  /// 3D files require them.
  pub cover_image: MediaFileCoverImageDetails,

  /// User info.
  pub maybe_creator_user: Option<UserDetailsLight>,

  /// File visibility.
  pub creator_set_visibility: Visibility,

  /// The foreign key to the prompt used to generate the media, if applicable.
  pub maybe_prompt_token: Option<PromptToken>,

  /// The name or title of the media file (optional)
  pub maybe_title: Option<String>,

  /// The original filename for uploaded files, if they were provided.
  /// In the future we'll provide our own internal optional filenames.
  pub maybe_original_filename: Option<String>,

  /// Duration for audio and video files, if available.
  /// Measured in milliseconds.
  pub maybe_duration_millis: Option<u64>,

  pub created_at: DateTime<Utc>,
  pub updated_at: DateTime<Utc>,

  // /// Text transcripts for TTS, etc.
  // pub maybe_text_transcript: Option<String>,

  // NB: This is in the old APIs, but it's irrelevant now.
  // /// If this is an engine/3D asset, this is the broad category (scene,
  // /// animation, etc.) of that object.
  // /// This can also be used for filtering in list/batch endpoints.
  // pub maybe_engine_category: Option<MediaFileEngineCategory>,

  // NB: This is in the old APIs, but it's irrelevant now.
  // /// If this is an engine/3D asset for an animation or a rig that can
  // /// be animated with either (or both) skeletal or blend shape animations,
  // /// this describes the animation regime used or supported.
  // pub maybe_animation_type: Option<MediaFileAnimationType>,

  // NB: This is in the old APIs, but it's irrelevant now.
  // /// If the media file has a subtype, we'll report it.
  // /// This is mostly used for Bevy engine files.
  // #[deprecated(note="This was for the Bevy engine. Do not use.")]
  // pub maybe_media_subtype: Option<MediaFileSubtype>,

  // NB: This is in the old APIs, but it's irrelevant now.
  // /// Extension for the engine to load over remote:// URLs.
  // #[deprecated(note="This was for the Bevy engine. Do not use.")]
  // pub maybe_engine_extension: Option<String>,

  // NB: This is in the old APIs, but it's irrelevant now.
  // /// (DEPRECATED) URL path to the media file
  // #[deprecated(note="This field doesn't point to the full URL. Use media_links instead to leverage the CDN.")]
  // pub public_bucket_path: String,

  // NB: This is in the old APIs, but it's irrelevant now.
  // /// (DEPRECATED) Full URL to the media file
  // #[deprecated(note="This points to the bucket. Use media_links instead to leverage the CDN.")]
  // pub public_bucket_url: String,

  // NB: This is in the old APIs, but it's irrelevant now.
  // // Provenance Data
  // pub origin_product: MediaFileOriginProductCategory,
  // pub origin_category: MediaFileOriginCategory,
  // pub maybe_origin_model_type: Option<MediaFileOriginModelType>,
  // pub maybe_origin_model_token: Option<String>,
  // pub maybe_origin_filename: Option<String>,

  // /// Possible model info (if generated by inference)
  // pub maybe_model_weight_info: Option<ListBatchGeneratedMediaFilesModelInfo>,

  // /// The file was uploaded by the user.
  // /// This does not include files generated on the client side, like studio renders.
  // pub is_user_upload: bool,

  // /// The file was created by the system.
  // /// This includes files generated on the client side, like studio renders.
  // pub is_intermediate_system_file: bool,

  // NB: Legacy baggage. Killing this field.
  // /// OPTIONAL. Details on live portrait generated media files,
  // /// if this is a live portrait generated file.
  // pub maybe_live_portrait_details: Option<MediaFileLivePortraitDetails>,

  // NB: Legacy baggage. Killing this field.
  // /// For Comfy / Video Style Transfer jobs, this might include
  // /// the name of the selected style.
  // pub maybe_style_name: Option<StyleTransferName>,

  // /// We can simulate media files for "tts_results" records.
  // /// If this is set as true, this informs the frontend and API callers not to treat
  // /// the token as a media file and improperly assume it can be used with the rest of
  // /// the media file APIs.
  // pub is_emulated_media_file: bool,

  // /// Statistics about the media file
  // pub stats: SimpleEntityStats,
}

// #[derive(Serialize, Deserialize, ToSchema)]
// pub struct ListBatchGeneratedMediaFilesModelInfo {
//   pub weight_token: ModelWeightToken,
//   pub weight_type: PublicWeightsType,
//   pub weight_category: WeightsCategory,
//   pub title: String,
// 
//   /// Cover images are small descriptive images that can be set for any model.
//   /// If a cover image is set, this is the path to the asset.
//   pub maybe_cover_image_public_bucket_path: Option<String>,
// 
//   /// NB: Technically this shouldn't be a nullable field, but since there are so many
//   /// joins we'll relax that this must exist (for now).
//   pub maybe_weight_creator: Option<UserDetailsLight>,
// }
