pub mod generate_kling_1_6_pro_video_handler;
pub mod generate_kling_2_1_master_video_handler;
pub mod generate_kling_2_1_pro_video_handler;
pub mod generate_seedance_1_0_lite_image_to_video_handler;
pub mod generate_veo_2_image_to_video_handler;