export enum ToolbarNodeButtonNames {
  TRANSFORM = "TRANSFORM",
  CHROMA = "CRHOMA",
  AI_STYLIZE = "AI_STYLIZE",
  SEGMENTATION = "SEGMENTATION",
  DELETE = "DELETE",
  MOVE_LAYER_UP = "MOVE_LAYER_UP",
  MOVE_LAYER_DOWN = "MOVE_LAYER_DOWN",
  DOWNLOAD = "DOWNLOAD",
}
