// NB: Incrementally getting rid of build warnings...
#![forbid(unused_imports)]
#![forbid(unused_mut)]
#![forbid(unused_variables)]

use crate::queries::users::user::create::create_account_error::CreateAccountError;
use crate::queries::users::user::create::create_account_generic::{create_account_generic, GenericCreateAccountArgs};
use crate::utils::transactor::Transactor;
use enums::by_table::users::user_signup_method::UserSignupMethod;
use enums::by_table::users::user_signup_source::UserSignupSource;
use tokens::tokens::users::UserToken;

/// Stripe checkout sessions do not have a real email address or password.
/// The user will create these once the checkout session is completed.
/// The password hash field is nullable, so we can't leave it null/empty.
const SSO_PASSWORD : &str = "*";

pub struct CreateAccountFromStripeCheckoutArgs<'a> {
  // NB: Username will likely be generated by our code, not the user.
  pub username: &'a str,
  pub display_name: &'a str,

  // NB: Email will likely be generated by our code, not the user.
  pub email_address: &'a str,
  pub email_gravatar_hash: &'a str,

  pub ip_address: &'a str,
  pub maybe_source: Option<UserSignupSource>,

  /// Comma separated string of feature flags.
  pub maybe_feature_flags: Option<&'a str>,
}

pub async fn create_account_from_stripe_checkout(
  args: CreateAccountFromStripeCheckoutArgs<'_>,
  transactor: Transactor<'_, '_>,
) -> Result<UserToken, CreateAccountError>
{
  let result= create_account_generic(
    GenericCreateAccountArgs {
      maybe_signup_method: Some(UserSignupMethod::StripeCheckout),

      ip_address: args.ip_address,
      maybe_feature_flags: args.maybe_feature_flags,
      maybe_source: args.maybe_source,

      // These are synthetic user accounts that are being eagerly created
      // If the user abandons the onboarding flow, they can be deleted later.
      is_temporary: true,
      was_eagerly_provisioned: true,

      // Stripe checkout users have randomly generated usernames
      username: args.username,
      display_name: args.display_name,
      username_is_generated: true,
      username_is_not_customized: true,

      // Stripe checkout users have NO REAL EMAIL ADDRESS yet.
      // Stripe will tell us what their email address is once
      // they complete the checkout (or the user can update it,
      // and their write wins.)
      email_address: args.email_address,
      email_gravatar_hash: args.email_gravatar_hash,
      email_confirmed_by_google: false,
      email_is_synthetic: true,

      // SSO accounts start without a password
      password_hash: SSO_PASSWORD,
      is_without_password: true,

      // NB: This is just for testing.
      maybe_user_token: None,
    },
    transactor,
  ).await?;

  Ok(result.user_token)
}
