mod add_control_plane_routes;
mod add_credits_routes;
mod add_generate_routes;
mod add_stripe_artcraft_routes;
mod add_subscription_routes;
mod add_webhook_routes;
mod job_routes;
mod media_files_routes;
mod moderation_routes;
mod tag_routes;
mod user_routes;
mod weights_routes;
pub (super) mod legacy_routes;
pub mod add_routes;
mod add_tts_routes;
mod featured_item_routes;