pub mod add_routes;
pub mod add_studio_gen2_routes;
pub mod beta_key_routes;
pub mod job_routes;
pub mod media_files_routes;
pub mod model_download_routes;
pub mod moderation_routes;
pub mod user_routes;
pub mod weights_routes;
pub mod workflow_routes;
mod tag_routes;
mod add_image_studio_routes;