mod add_control_plane_routes;
mod add_credits_routes;
mod add_generate_routes;
mod add_image_studio_routes;
mod add_stripe_artcraft_routes;
mod add_studio_gen2_routes;
mod add_webhook_routes;
mod beta_key_routes;
mod job_routes;
mod media_files_routes;
mod model_download_routes;
mod moderation_routes;
mod tag_routes;
mod user_routes;
mod weights_routes;
mod workflow_routes;
pub mod add_routes;
mod add_subscription_routes;