use std::error::Error;
use std::fmt::{Display, Formatter};

#[derive(Debug)]
pub enum SoraSpecificApiError {
  /// Failed to generate a bearer token despite the `200 OK` response.
  /// This has been generated by sending old/expired session cookies or empty cookies.
  FailedToGenerateBearerToken,

  /// Sora requires users to set up an account username before they can generate images.
  /// This requires the user to set up that username.
  SoraUsernameNotYetCreated,

  /// We're sending too many tasks to Sora.
  /// Sora is telling us to cool it.
  TooManyConcurrentTasks,

  // TODO: Try to make concrete error types for these distinct cases.
  /// Unauthorized, cookie and/or bearer token expired. We'll need to ask for a refreshed login.
  ///
  /// Example message, e.g. from the upload endpoint:
  ///   {
  ///     "error": {
  ///       "message": "Your authentication token has expired. Please try signing in again.",
  ///       "type": "invalid_request_error",
  ///       "param": null,
  ///       "code": "token_expired"
  ///     }
  ///   }
  UnauthorizedCookieOrBearerExpired,
}

impl Error for SoraSpecificApiError {}

impl Display for SoraSpecificApiError {
  fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
    match self {
      Self::FailedToGenerateBearerToken => write!(f, "Failed to generate bearer token. Probably invalid or expired session cookies."),
      Self::SoraUsernameNotYetCreated => write!(f, "Sora username not yet created. Please create a username in the Sora app or website."),
      Self::TooManyConcurrentTasks => write!(f, "Too many concurrent tasks. Please wait."),
      Self::UnauthorizedCookieOrBearerExpired => write!(f, "Unauthorized: cookie and/or bearer token expired"),
    }
  }
}
