import { GenerationProvider } from "@storyteller/api-enums";
import { ImageModel } from "../classes/ImageModel.js";
import { ModelCreator } from "../classes/metadata/ModelCreator.js";
import { ModelTag } from "../classes/metadata/ModelTag.js";

// TODO: Some of the model configs, such as generation counts, are authoritatively controlled in `legacy/Models.ts`

export const IMAGE_MODELS: ImageModel[] = [
  new ImageModel({
    id: "grok_image",
    tauriId: "grok_image",
    fullName: "Grok",
    category: "image",
    creator: ModelCreator.Grok,
    providers: [
      GenerationProvider.Grok, 
    ],
    selectorName: "Grok",
    selectorDescription: "Fast af",
    selectorBadges: ["10 sec."],
    defaultGenerationCount: 4,
    maxGenerationCount: 6,
    canUseImagePrompt: false,
    maxImagePromptCount: 6,
    progressBarTime: 10000,
    canChangeAspectRatio: true,
  }),
  new ImageModel({
    id: "midjourney",
    tauriId: "midjourney",
    fullName: "Midjourney",
    category: "image",
    creator: ModelCreator.Midjourney,
    providers: [
      GenerationProvider.Midjourney
    ],
    selectorName: "Midjourney",
    selectorDescription: "Stunning style and quality",
    selectorBadges: ["45 sec."],
    maxGenerationCount: 4,
    defaultGenerationCount: 4,
    canUseImagePrompt: false,
    maxImagePromptCount: 6,
    progressBarTime: 45000,
    canChangeAspectRatio: true,
  }),
  new ImageModel({
    id: "flux_pro_1_1_ultra",
    tauriId: "flux_pro_11_ultra",
    fullName: "Flux Pro 1.1 Ultra",
    category: "image",
    creator: ModelCreator.BlackForestLabs,
    selectorName: "Flux Pro 1.1 Ultra",
    selectorDescription: "Higher quality model",
    selectorBadges: ["35 sec."],
    maxGenerationCount: 4,
    defaultGenerationCount: 4,
    canUseImagePrompt: true,
    maxImagePromptCount: 6,
    progressBarTime: 35000,
    canChangeAspectRatio: true,
  }),
  new ImageModel({
    id: "flux_pro_1_1",
    tauriId: "flux_pro_11",
    fullName: "Flux Pro 1.1",
    category: "image",
    creator: ModelCreator.BlackForestLabs,
    selectorName: "Flux Pro 1.1",
    selectorDescription: "High quality model",
    selectorBadges: ["10 sec."],
    maxGenerationCount: 4,
    defaultGenerationCount: 4,
    canUseImagePrompt: true,
    maxImagePromptCount: 6,
    progressBarTime: 10000,
    canChangeAspectRatio: true,
  }),
  new ImageModel({
    id: "flux_1_dev",
    tauriId: "flux_1_dev",
    fullName: "Flux 1 Dev",
    category: "image",
    creator: ModelCreator.BlackForestLabs,
    selectorName: "Flux 1 Dev",
    selectorDescription: "Fast, but lower quality",
    selectorBadges: ["10 sec."],
    maxGenerationCount: 4,
    defaultGenerationCount: 4,
    canUseImagePrompt: true,
    maxImagePromptCount: 6,
    progressBarTime: 10000,
    canChangeAspectRatio: true,
  }),
  new ImageModel({
    id: "flux_1_schnell",
    tauriId: "flux_1_schnell",
    fullName: "Flux 1 Schnell",
    category: "image",
    creator: ModelCreator.BlackForestLabs,
    selectorName: "Flux 1 Schnell",
    selectorDescription: "Fastest image gen, but lowest quality",
    selectorBadges: ["10 sec."],
    maxGenerationCount: 4,
    defaultGenerationCount: 4,
    canUseImagePrompt: true,
    maxImagePromptCount: 6,
    progressBarTime: 10000,
    canChangeAspectRatio: true,
  }),
  new ImageModel({
    id: "gemini_25_flash",
    tauriId: "gemini_25_flash",
    fullName: "Gemini 2.5 Flash",
    category: "image",
    creator: ModelCreator.Google,
    selectorName: "Nano Banana",
    selectorDescription: "Incredibly instructive editing",
    selectorBadges: ["25 sec."],
    maxGenerationCount: 4,
    defaultGenerationCount: 1,
    canEditImages: true,
    canUseImagePrompt: true,
    maxImagePromptCount: 6,
    canTextToImage: false,
    tags: [ModelTag.InstructiveEdit],
    progressBarTime: 25000,
    // canChangeResolution: true,
    canChangeAspectRatio: true,
  }),
  new ImageModel({
    id: "nano_banana_pro",
    tauriId: "nano_banana_pro",
    fullName: "Nano Banana Pro",
    category: "image",
    creator: ModelCreator.Google,
    selectorName: "Nano Banana Pro",
    selectorDescription: "Extremely powerful",
    selectorBadges: ["30 sec."],
    maxGenerationCount: 4,
    defaultGenerationCount: 1,
    canEditImages: true,
    canUseImagePrompt: true,
    maxImagePromptCount: 4,
    canTextToImage: true,
    tags: [ModelTag.InstructiveEdit],
    progressBarTime: 25000,
    canChangeResolution: true,
    canChangeAspectRatio: true,
  }),
  new ImageModel({
    id: "gpt_image_1",
    tauriId: "gpt_image_1",
    fullName: "GPT Image 1 (GPT-4o)",
    category: "image",
    creator: ModelCreator.OpenAi,
    providers: [
      GenerationProvider.Artcraft, 
      GenerationProvider.Sora
    ],
    selectorName: "GPT Image 1 (GPT-4o)",
    selectorDescription: "Slow, but super smart",
    selectorBadges: ["60 sec."],
    maxGenerationCount: 4,
    defaultGenerationCount: 1,
    tags: [ModelTag.InstructiveEdit],
    canEditImages: true,
    canUseImagePrompt: true,
    maxImagePromptCount: 6,
    progressBarTime: 60000,
    canChangeAspectRatio: true,
  }),
  new ImageModel({
    id: "gpt_image_1p5",
    tauriId: "gpt_image_1p5",
    fullName: "GPT Image 1.5",
    category: "image",
    creator: ModelCreator.OpenAi,
    selectorName: "GPT Image 1.5",
    selectorDescription: "Faster, improved",
    selectorBadges: ["60 sec."],
    maxGenerationCount: 4,
    defaultGenerationCount: 1,
    tags: [ModelTag.InstructiveEdit],
    canEditImages: true,
    canUseImagePrompt: true,
    maxImagePromptCount: 6,
    progressBarTime: 60000,
    canChangeAspectRatio: true,
  }),
  new ImageModel({
    id: "seedream_4",
    tauriId: "seedream_4",
    fullName: "Seedream 4",
    category: "image",
    creator: ModelCreator.OpenAi,
    selectorName: "Seedream 4",
    selectorDescription: "Fast",
    selectorBadges: ["60 sec."],
    maxGenerationCount: 4,
    defaultGenerationCount: 1,
    tags: [ModelTag.InstructiveEdit],
    canEditImages: true,
    canUseImagePrompt: true,
    maxImagePromptCount: 6,
    progressBarTime: 60000,
    canChangeAspectRatio: true,
  }),
  new ImageModel({
    id: "seedream_4p5",
    tauriId: "seedream_4p5",
    fullName: "Seedream 4.5",
    category: "image",
    creator: ModelCreator.OpenAi,
    selectorName: "Seedream 4.5",
    selectorDescription: "Fast",
    selectorBadges: ["60 sec."],
    maxGenerationCount: 4,
    defaultGenerationCount: 1,
    tags: [ModelTag.InstructiveEdit],
    canEditImages: true,
    canUseImagePrompt: true,
    maxImagePromptCount: 6,
    progressBarTime: 60000,
    canChangeAspectRatio: true,
  }),
  new ImageModel({
    id: "flux_pro_kontext_max",
    tauriId: "flux_pro_kontext_max",
    fullName: "Flux Pro Kontext Max",
    category: "image",
    creator: ModelCreator.BlackForestLabs,
    selectorName: "Flux Pro Kontext Max",
    selectorDescription: "Fast instructive editing",
    selectorBadges: ["20 sec."],
    maxGenerationCount: 4,
    defaultGenerationCount: 4,
    canEditImages: true,
    canTextToImage: false,
    tags: [ModelTag.InstructiveEdit],
    progressBarTime: 20000,
    canChangeAspectRatio: true,
  }),
  new ImageModel({
    id: "flux_pro_inpaint",
    tauriId: "flux_pro_1",
    fullName: "Flux Pro Inpaint",
    category: "image",
    creator: ModelCreator.BlackForestLabs,
    selectorName: "Flux Pro (Inpainting)",
    selectorDescription: "Fast inpainting",
    selectorBadges: ["30 sec."],
    maxGenerationCount: 1, // NB: Fal only allows one image for some reason!
    defaultGenerationCount: 1, // NB: Fal only allows one image for some reason!
    canEditImages: true,
    usesInpaintingMask: true,
    editingIsInpainting: true,
    canTextToImage: false,
    progressBarTime: 30000,
    canChangeAspectRatio: true,
  }),
  new ImageModel({
    id: "flux_dev_juggernaut_inpaint",
    tauriId: "flux_dev_juggernaut",
    fullName: "Flux Dev Juggernaut Inpaint",
    category: "image",
    creator: ModelCreator.BlackForestLabs,
    selectorName: "Flux Dev Juggernaut",
    selectorDescription: "Fast inpainting, low quality",
    selectorBadges: ["10 sec."],
    maxGenerationCount: 4,
    defaultGenerationCount: 4,
    canEditImages: true,
    usesInpaintingMask: true,
    editingIsInpainting: true,
    canTextToImage: false,
    progressBarTime: 10000,
    canChangeAspectRatio: true,
  }),
];

export const IMAGE_MODELS_BY_ID: Map<string, ImageModel> = new Map(
  IMAGE_MODELS.map((model) => [model.id, model]),
);

if (IMAGE_MODELS_BY_ID.size !== IMAGE_MODELS.length) {
  throw new Error("All image models must have unique IDs");
}
