import { GenerationProvider } from "@storyteller/api-enums";
import { VideoModel } from "../classes/VideoModel.js";
import { ModelCreator } from "../classes/metadata/ModelCreator.js";
import { SizeIconOption } from "../classes/metadata/SizeOption.js";

export const VIDEO_MODELS: VideoModel[] = [
  new VideoModel({
    id: "grok_video",
    tauriId: "grok_video",
    fullName: "Grok Video",
    category: "video",
    creator: ModelCreator.Grok,
    providers: [
      GenerationProvider.Grok
    ],
    selectorName: "Grok Video",
    selectorDescription: "Fastest video model",
    selectorBadges: ["20 sec."],
    startFrame: true,
    endFrame: false,
    requiresImage: true,
    progressBarTime: 50000,
    sizeOptions: [
      {
        tauriValue: "landscape",
        textLabel: "Landscape",
        icon: SizeIconOption.Landscape,
      },
      {
        tauriValue: "portrait",
        textLabel: "Portrait",
        icon: SizeIconOption.Portrait,
      },
      {
        tauriValue: "square",
        textLabel: "Square",
        icon: SizeIconOption.Square,
      },
    ],
  }),
  new VideoModel({
    id: "kling_1_6_pro",
    tauriId: "kling_1.6_pro",
    fullName: "Kling 1.6 Pro",
    category: "video",
    creator: ModelCreator.Kling,
    selectorName: "Kling 1.6 Pro",
    selectorDescription: "Fast video model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: true,
    requiresImage: true,
    progressBarTime: 100000,
    generateWithSound: false,
  }),
  new VideoModel({
    id: "kling_2_1_pro",
    tauriId: "kling_2.1_pro",
    fullName: "Kling 2.1 Pro",
    category: "video",
    creator: ModelCreator.Kling,
    selectorName: "Kling 2.1 Pro",
    selectorDescription: "Fast video model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: true,
    requiresImage: true,
    progressBarTime: 100000,
    generateWithSound: false,
  }),
  new VideoModel({
    id: "kling_2_1_master",
    tauriId: "kling_2.1_master",
    fullName: "Kling 2.1 Master",
    category: "video",
    creator: ModelCreator.Kling,
    selectorName: "Kling 2.1 Master",
    selectorDescription: "Fast video model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: false,
    requiresImage: true,
    progressBarTime: 100000,
    generateWithSound: false,
  }),
  new VideoModel({
    id: "kling_2p5_turbo_pro",
    tauriId: "kling_2p5_turbo_pro",
    fullName: "Kling 2.5 Turbo Pro",
    category: "video",
    creator: ModelCreator.Kling,
    selectorName: "Kling 2.5 Turbo Pro",
    selectorDescription: "Fast video model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: true,
    requiresImage: false,
    progressBarTime: 100000,
    generateWithSound: false,
  }),
  new VideoModel({
    id: "kling_2p6_pro",
    tauriId: "kling_2p6_pro",
    fullName: "Kling 2.6 Pro",
    category: "video",
    creator: ModelCreator.Kling,
    selectorName: "Kling 2.6 Pro",
    selectorDescription: "Fast video model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: false,
    requiresImage: true,
    progressBarTime: 100000,
    generateWithSound: false,
  }),
  new VideoModel({
    id: "seedance_1_0_lite",
    tauriId: "seedance_1.0_lite",
    fullName: "Seedance 1.0 Lite",
    category: "video",
    creator: ModelCreator.Bytedance,
    selectorName: "Seedance 1.0 Lite",
    selectorDescription: "Fast video model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: false,
    requiresImage: true,
    progressBarTime: 100000,
  }),
  new VideoModel({
    id: "sora_2",
    tauriId: "sora_2",
    fullName: "Sora 2",
    category: "video",
    creator: ModelCreator.OpenAi,
    providers: [
      GenerationProvider.Artcraft,
      GenerationProvider.Sora,
    ],
    selectorName: "Sora 2",
    selectorDescription: "Smart video model",
    selectorBadges: ["2 min."],
    startFrame: false,
    endFrame: false,
    requiresImage: false,
    sizeOptions: [
      {
        tauriValue: "landscape",
        textLabel: "Landscape",
        icon: SizeIconOption.Landscape,
      },
      {
        tauriValue: "portrait",
        textLabel: "Portrait",
        icon: SizeIconOption.Portrait,
      },
    ],
    progressBarTime: 100000,
  }),
  new VideoModel({
    id: "sora_2_pro",
    tauriId: "sora_2_pro",
    fullName: "Sora 2 Pro",
    category: "video",
    creator: ModelCreator.OpenAi,
    selectorName: "Sora 2 Pro",
    selectorDescription: "Smart video model",
    selectorBadges: ["2 min."],
    startFrame: false,
    endFrame: false,
    requiresImage: false,
    sizeOptions: [
      {
        tauriValue: "landscape",
        textLabel: "Landscape",
        icon: SizeIconOption.Landscape,
      },
      {
        tauriValue: "portrait",
        textLabel: "Portrait",
        icon: SizeIconOption.Portrait,
      },
    ],
    progressBarTime: 100000,
  }),
  new VideoModel({
    id: "veo_2",
    tauriId: "veo_2",
    fullName: "Google Veo 2",
    category: "video",
    creator: ModelCreator.Google,
    selectorName: "Google Veo 2",
    selectorDescription: "Fast video model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: false,
    requiresImage: true,
    generateWithSound: false,
    progressBarTime: 100000,
  }),
  new VideoModel({
    id: "veo_3",
    tauriId: "veo_3",
    fullName: "Google Veo 3",
    category: "video",
    creator: ModelCreator.Google,
    selectorName: "Google Veo 3",
    selectorDescription: "Slow, high-quality model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: false,
    requiresImage: true,
    generateWithSound: true,
    progressBarTime: 100000,
  }),
  new VideoModel({
    id: "veo_3_fast",
    tauriId: "veo_3_fast",
    fullName: "Google Veo 3 Fast",
    category: "video",
    creator: ModelCreator.Google,
    selectorName: "Google Veo 3 Fast",
    selectorDescription: "High-quality model (faster)",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: false,
    requiresImage: true,
    generateWithSound: true,
    progressBarTime: 100000,
  }),
  new VideoModel({
    id: "veo_3p1",
    tauriId: "veo_3p1",
    fullName: "Google Veo 3.1",
    category: "video",
    creator: ModelCreator.Google,
    selectorName: "Google Veo 3.1",
    selectorDescription: "Slow, high-quality model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: false,
    requiresImage: true,
    generateWithSound: true,
    progressBarTime: 100000,
  }),
  new VideoModel({
    id: "veo_3p1_fast",
    tauriId: "veo_3p1_fast",
    fullName: "Google Veo 3.1 Fast",
    category: "video",
    creator: ModelCreator.Google,
    selectorName: "Google Veo 3.1 Fast",
    selectorDescription: "High-quality model (faster)",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: false,
    requiresImage: true,
    generateWithSound: true,
    progressBarTime: 100000,
  }),
];
